# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# ✅ Necessário para Firebase Swift com frameworks estáticos
use_modular_headers!

# ✅ FORÇANDO frameworks estáticos
use_frameworks! :linkage => :static

target 'CagaCoins' do
  config = use_native_modules!

  # ⚠️ Não declare pods Firebase manualmente
  # @react-native-firebase/* já cuida disso automaticamente

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

